package ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class Dialog extends JDialog {
        private JPanel contentPane;
        private JButton ok;
        private JLabel text;

        public Dialog(String text) {
                this.text.setText(text);
                setContentPane(contentPane);
                setModal(true);
                this.pack();
                this.setLocationRelativeTo(null);
                getRootPane().setDefaultButton(ok);
                initListener();
        }

        private void initListener() {
                ok.addActionListener(e -> dispose());

                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                addWindowListener(new WindowAdapter() {
                        public void windowClosing(WindowEvent e) {
                                dispose();
                        }
                });

                contentPane.registerKeyboardAction(e -> dispose(),
                                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        }

        {
                // GUI initializer generated by IntelliJ IDEA GUI Designer
                // >>> IMPORTANT!! <<<
                // DO NOT EDIT OR ADD ANY CODE HERE!
                $$$setupUI$$$();
        }

        /**
         * Method generated by IntelliJ IDEA GUI Designer
         * >>> IMPORTANT!! <<<
         * DO NOT edit this method OR call it in your code!
         *
         * @noinspection ALL
         */
        private void $$$setupUI$$$() {
                contentPane = new JPanel();
                contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1,
                                new Insets(10, 10, 10, 10), -1, -1));
                final JPanel panel1 = new JPanel();
                panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1,
                                -1));
                contentPane.add(panel1,
                                new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                1, null, null, null, 0, false));
                final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
                panel1.add(spacer1,
                                new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1,
                                                null, null, null, 0, false));
                final JPanel panel2 = new JPanel();
                panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1,
                                -1));
                panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                null, null, null, 0, false));
                ok = new JButton();
                ok.setText("OK");
                panel2.add(ok, new com.intellij.uiDesigner.core.GridConstraints(0, 0,
                                1, 1,
                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                false));
                final JPanel panel3 = new JPanel();
                panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1,
                                -1));
                contentPane.add(panel3,
                                new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                null, null, null, 0, false));
                text = new JLabel();
                text.setText("PASWROD BLABABAKA");
                panel3.add(text, new com.intellij.uiDesigner.core.GridConstraints(0,
                                0, 1, 1,
                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                false));
        }

        /**
         * @noinspection ALL
         */
        public JComponent $$$getRootComponent$$$() {
                return contentPane;
        }
}
