package ui;

import entity.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class Login extends JFrame {
    private final service.User userService;

    private JTextField username;
    private JTextField password;
    private JButton login;
    private JPanel panel;
    private JLabel register;

    public Login(service.User userService) {
        super("Login");
        this.userService = userService;

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(panel);
        this.setLocationRelativeTo(null);
        this.pack();

        initListener();
    }

    void initListener() {
        login.addActionListener(e -> {
            if (username.getText().length() == 0 || password.getText().length() == 0) {
                Dialog dialog = new Dialog("Mohon Isi Kolom Yang Kosong");
                dialog.setVisible(true);
                return;
            }

            boolean usernameIsExist = userService.isUsernameAvailable(username.getText());
            if (usernameIsExist) {
                Dialog dialog = new Dialog("Username Tidak Ditemukan");
                dialog.setVisible(true);
                return;
            }

            User user = new User(username.getText(), password.getText());
            Boolean logged = userService.login(user);
            String text;
            if (logged) {
                text = "Berhasil Login";
            } else {
                text = "Password Salah";
            }

            Dialog dialog = new Dialog(text);
            dialog.setVisible(true);
        });

        register.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                Register register = new Register(userService);
                register.setVisible(true);
                dispose();
            }

            @Override
            public void mousePressed(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseReleased(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseEntered(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseExited(MouseEvent mouseEvent) {

            }
        });
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6,
                1, new Insets(15, 15, 15, 15), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Username");
        panel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0,
                0, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        username = new JTextField();
        username.setText("");
        panel.add(username,
                new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1),
                        null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Password");
        panel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2,
                0, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        login = new JButton();
        login.setText("Login");
        panel.add(login, new com.intellij.uiDesigner.core.GridConstraints(4,
                0, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                        | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        register = new JLabel();
        register.setText("Daftar Disini");
        panel.add(register,
                new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        password = new JTextField();
        panel.add(password,
                new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1),
                        null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
